### ISSUE TITLE
How to use this plugin?

### ISSUE THREAD

**Issue by blackbusters** [clouedoc/puppeteer-extra-plugin-session#2]
Sorry for my stupid question, but i already spent hours on trying to get this plugin to work and still can't.

I've installed it from npm using : npm install puppeteer-extra-plugin-session

And here is my sample code :
```
const puppeteer = require('puppeteer-extra');
var sessionplugin = require('puppeteer-extra-plugin-session');
puppeteer.use(sessionplugin());
```

with above code, i always got error :
TypeError: sessionplugin is not a function

when I changed to this code :
```
const puppeteer = require('puppeteer-extra');
var sessionplugin = require('puppeteer-extra-plugin-session');
puppeteer.use(sessionplugin);
```

I got this warning message :
Warning: Plugin is not derived from PuppeteerExtraPlugin, ignoring. { PLUGIN_NAME: [Getter], SessionPlugin: [Getter], default: [Function] }

and it doesn't seem to reload this plugin.

Oddly, I can use puppeteer-extra-plugin-stealth properly with this code :
```
const puppeteer = require('puppeteer-extra')
const StealthPlugin = require('puppeteer-extra-plugin-stealth')
puppeteer.use(StealthPlugin())
```

Can someone explain me what to do to fix it?

I'm currently using node JS v12.22.11, npm v6.14.16

Thank you..

**Comment by clouedoc** [comment]
Hello, thanks for opening this issue.
Are you using the latest version of puppeteer-extra?
Also, try `puppeteer.use(new sessionplugin());`
Let me know your results. I'm still maintaining this plugin.

**Comment by blackbusters** [comment]
Hi, thank you for the reply.

yes i'm using puppeteer-extra v3.2.3, and i also tried puppeteer-extra next : "^3.1.16-next.149".

I tried with this code :
const puppeteer = require('puppeteer-extra');
var sessionplugin = require('puppeteer-extra-plugin-session');
puppeteer.use(new sessionplugin());

But still got error :
TypeError: sessionplugin is not a constructor

is there any minimum requirement for node or npm version?

**Comment by clouedoc** [comment]
> is there any minimum requirement for node or npm version?

Everything >= Nove 14 should be fine. What are your versions?

**Comment by blackbusters** [comment]
I was using v12, but after update to v17 still having same problem...

**Comment by clouedoc** [comment]
I suggest you keep using v16; some projects might not support v17.
I'll take a look at this problem as soon as I can. Expect a fix by approx. Monday.

**Comment by clouedoc** [comment]
Hi, I've figured it out.

Here is some demo code for you:

```js
const puppeteer = require("puppeteer-extra")
puppeteer.use(require('puppeteer-extra-plugin-session').default())
```

Let me know if you need any more help concerning this project.
