### ISSUE TITLE
How to save session for later use

### ISSUE THREAD

**Issue by stachic** [clouedoc/puppeteer-extra-plugin-session#5]
Hey! Sorry for such a noob question, but I have no idea how to save sessionData into a file that I could reuse in different browser instance. Thanks for making this package!

**Comment by clouedoc** [comment]
Hello, the simplest way to go about this would be to use a combination of JSON.stringify and fs.writeFileSync.
This is more a kind of tech-support problem rather than an actual software issue, so I will close this thread. However, you are welcome to seek more help here: https://extra.community
